/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FlightAvailabilityResponseBound;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * FlightAvailabilityGroupOfFlights
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-25T11:48:12.193Z[GMT]")
public class FlightAvailabilityGroupOfFlights {
  @SerializedName("bounds")
  private List<List<FlightAvailabilityResponseBound>> bounds = null;

  public FlightAvailabilityGroupOfFlights bounds(List<List<FlightAvailabilityResponseBound>> bounds) {
    this.bounds = bounds;
    return this;
  }

  public FlightAvailabilityGroupOfFlights addBoundsItem(List<FlightAvailabilityResponseBound> boundsItem) {
    if (this.bounds == null) {
      this.bounds = new ArrayList<List<FlightAvailabilityResponseBound>>();
    }
    this.bounds.add(boundsItem);
    return this;
  }

   /**
   * Get bounds
   * @return bounds
  **/
  @Schema(description = "")
  public List<List<FlightAvailabilityResponseBound>> getBounds() {
    return bounds;
  }

  public void setBounds(List<List<FlightAvailabilityResponseBound>> bounds) {
    this.bounds = bounds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightAvailabilityGroupOfFlights flightAvailabilityGroupOfFlights = (FlightAvailabilityGroupOfFlights) o;
    return Objects.equals(this.bounds, flightAvailabilityGroupOfFlights.bounds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bounds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightAvailabilityGroupOfFlights {\n");
    
    sb.append("    bounds: ").append(toIndentedString(bounds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
