/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FlightBookingCustomerPax;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FlightBookingCustomer
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-24T22:56:10.425Z[GMT]")
public class FlightBookingCustomer {
  @SerializedName("address")
  private String address = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pax")
  private FlightBookingCustomerPax pax = null;

  @SerializedName("pax_id")
  private Integer paxId = null;

  @SerializedName("phone_number")
  private String phoneNumber = null;

  public FlightBookingCustomer address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public FlightBookingCustomer email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public FlightBookingCustomer id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public FlightBookingCustomer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FlightBookingCustomer pax(FlightBookingCustomerPax pax) {
    this.pax = pax;
    return this;
  }

   /**
   * Get pax
   * @return pax
  **/
  @Schema(description = "")
  public FlightBookingCustomerPax getPax() {
    return pax;
  }

  public void setPax(FlightBookingCustomerPax pax) {
    this.pax = pax;
  }

  public FlightBookingCustomer paxId(Integer paxId) {
    this.paxId = paxId;
    return this;
  }

   /**
   * Get paxId
   * @return paxId
  **/
  @Schema(description = "")
  public Integer getPaxId() {
    return paxId;
  }

  public void setPaxId(Integer paxId) {
    this.paxId = paxId;
  }

  public FlightBookingCustomer phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @Schema(description = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightBookingCustomer flightBookingCustomer = (FlightBookingCustomer) o;
    return Objects.equals(this.address, flightBookingCustomer.address) &&
        Objects.equals(this.email, flightBookingCustomer.email) &&
        Objects.equals(this.id, flightBookingCustomer.id) &&
        Objects.equals(this.name, flightBookingCustomer.name) &&
        Objects.equals(this.pax, flightBookingCustomer.pax) &&
        Objects.equals(this.paxId, flightBookingCustomer.paxId) &&
        Objects.equals(this.phoneNumber, flightBookingCustomer.phoneNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, email, id, name, pax, paxId, phoneNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightBookingCustomer {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pax: ").append(toIndentedString(pax)).append("\n");
    sb.append("    paxId: ").append(toIndentedString(paxId)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
