/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FlightAirport
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-25T18:44:13.943Z[GMT]")
public class FlightAirport {
  @SerializedName("city_code")
  private String cityCode = null;

  @SerializedName("city_name")
  private String cityName = null;

  @SerializedName("country_code")
  private String countryCode = null;

  @SerializedName("country_name")
  private String countryName = null;

  @SerializedName("display")
  private String display = null;

  @SerializedName("iata")
  private String iata = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("number_of_airports_in_the_city")
  private Integer numberOfAirportsInTheCity = null;

  public FlightAirport cityCode(String cityCode) {
    this.cityCode = cityCode;
    return this;
  }

   /**
   * Get cityCode
   * @return cityCode
  **/
  @Schema(description = "")
  public String getCityCode() {
    return cityCode;
  }

  public void setCityCode(String cityCode) {
    this.cityCode = cityCode;
  }

  public FlightAirport cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * Get cityName
   * @return cityName
  **/
  @Schema(description = "")
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public FlightAirport countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @Schema(description = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public FlightAirport countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

   /**
   * Get countryName
   * @return countryName
  **/
  @Schema(description = "")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public FlightAirport display(String display) {
    this.display = display;
    return this;
  }

   /**
   * Get display
   * @return display
  **/
  @Schema(description = "")
  public String getDisplay() {
    return display;
  }

  public void setDisplay(String display) {
    this.display = display;
  }

  public FlightAirport iata(String iata) {
    this.iata = iata;
    return this;
  }

   /**
   * Get iata
   * @return iata
  **/
  @Schema(description = "")
  public String getIata() {
    return iata;
  }

  public void setIata(String iata) {
    this.iata = iata;
  }

  public FlightAirport name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FlightAirport numberOfAirportsInTheCity(Integer numberOfAirportsInTheCity) {
    this.numberOfAirportsInTheCity = numberOfAirportsInTheCity;
    return this;
  }

   /**
   * Get numberOfAirportsInTheCity
   * @return numberOfAirportsInTheCity
  **/
  @Schema(description = "")
  public Integer getNumberOfAirportsInTheCity() {
    return numberOfAirportsInTheCity;
  }

  public void setNumberOfAirportsInTheCity(Integer numberOfAirportsInTheCity) {
    this.numberOfAirportsInTheCity = numberOfAirportsInTheCity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightAirport flightAirport = (FlightAirport) o;
    return Objects.equals(this.cityCode, flightAirport.cityCode) &&
        Objects.equals(this.cityName, flightAirport.cityName) &&
        Objects.equals(this.countryCode, flightAirport.countryCode) &&
        Objects.equals(this.countryName, flightAirport.countryName) &&
        Objects.equals(this.display, flightAirport.display) &&
        Objects.equals(this.iata, flightAirport.iata) &&
        Objects.equals(this.name, flightAirport.name) &&
        Objects.equals(this.numberOfAirportsInTheCity, flightAirport.numberOfAirportsInTheCity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cityCode, cityName, countryCode, countryName, display, iata, name, numberOfAirportsInTheCity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightAirport {\n");
    
    sb.append("    cityCode: ").append(toIndentedString(cityCode)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    iata: ").append(toIndentedString(iata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    numberOfAirportsInTheCity: ").append(toIndentedString(numberOfAirportsInTheCity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
