/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FlightAirline
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-25T11:48:12.193Z[GMT]")
public class FlightAirline {
  @SerializedName("airline")
  private String airline = null;

  @SerializedName("bestPrice")
  private Integer bestPrice = null;

  @SerializedName("callsign")
  private String callsign = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("country_of_Origin")
  private String countryOfOrigin = null;

  @SerializedName("iata")
  private String iata = null;

  @SerializedName("icao")
  private String icao = null;

  @SerializedName("name")
  private String name = null;

  public FlightAirline airline(String airline) {
    this.airline = airline;
    return this;
  }

   /**
   * Get airline
   * @return airline
  **/
  @Schema(description = "")
  public String getAirline() {
    return airline;
  }

  public void setAirline(String airline) {
    this.airline = airline;
  }

  public FlightAirline bestPrice(Integer bestPrice) {
    this.bestPrice = bestPrice;
    return this;
  }

   /**
   * Get bestPrice
   * @return bestPrice
  **/
  @Schema(description = "")
  public Integer getBestPrice() {
    return bestPrice;
  }

  public void setBestPrice(Integer bestPrice) {
    this.bestPrice = bestPrice;
  }

  public FlightAirline callsign(String callsign) {
    this.callsign = callsign;
    return this;
  }

   /**
   * Get callsign
   * @return callsign
  **/
  @Schema(description = "")
  public String getCallsign() {
    return callsign;
  }

  public void setCallsign(String callsign) {
    this.callsign = callsign;
  }

  public FlightAirline code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public FlightAirline countryOfOrigin(String countryOfOrigin) {
    this.countryOfOrigin = countryOfOrigin;
    return this;
  }

   /**
   * Get countryOfOrigin
   * @return countryOfOrigin
  **/
  @Schema(description = "")
  public String getCountryOfOrigin() {
    return countryOfOrigin;
  }

  public void setCountryOfOrigin(String countryOfOrigin) {
    this.countryOfOrigin = countryOfOrigin;
  }

  public FlightAirline iata(String iata) {
    this.iata = iata;
    return this;
  }

   /**
   * Get iata
   * @return iata
  **/
  @Schema(description = "")
  public String getIata() {
    return iata;
  }

  public void setIata(String iata) {
    this.iata = iata;
  }

  public FlightAirline icao(String icao) {
    this.icao = icao;
    return this;
  }

   /**
   * Get icao
   * @return icao
  **/
  @Schema(description = "")
  public String getIcao() {
    return icao;
  }

  public void setIcao(String icao) {
    this.icao = icao;
  }

  public FlightAirline name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightAirline flightAirline = (FlightAirline) o;
    return Objects.equals(this.airline, flightAirline.airline) &&
        Objects.equals(this.bestPrice, flightAirline.bestPrice) &&
        Objects.equals(this.callsign, flightAirline.callsign) &&
        Objects.equals(this.code, flightAirline.code) &&
        Objects.equals(this.countryOfOrigin, flightAirline.countryOfOrigin) &&
        Objects.equals(this.iata, flightAirline.iata) &&
        Objects.equals(this.icao, flightAirline.icao) &&
        Objects.equals(this.name, flightAirline.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(airline, bestPrice, callsign, code, countryOfOrigin, iata, icao, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightAirline {\n");
    
    sb.append("    airline: ").append(toIndentedString(airline)).append("\n");
    sb.append("    bestPrice: ").append(toIndentedString(bestPrice)).append("\n");
    sb.append("    callsign: ").append(toIndentedString(callsign)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    countryOfOrigin: ").append(toIndentedString(countryOfOrigin)).append("\n");
    sb.append("    iata: ").append(toIndentedString(iata)).append("\n");
    sb.append("    icao: ").append(toIndentedString(icao)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
