/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * FlightBaseTraveller
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-25T18:44:13.943Z[GMT]")
public class FlightBaseTraveller {
  @SerializedName("birthDate")
  private String birthDate = null;

  @SerializedName("firstname")
  private String firstname = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("nationality")
  private String nationality = null;

  @SerializedName("passportExpirationDate")
  private LocalDate passportExpirationDate = null;

  @SerializedName("passportNumber")
  private String passportNumber = null;

  @SerializedName("sex")
  private String sex = null;

  public FlightBaseTraveller birthDate(String birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Get birthDate
   * @return birthDate
  **/
  @Schema(description = "")
  public String getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(String birthDate) {
    this.birthDate = birthDate;
  }

  public FlightBaseTraveller firstname(String firstname) {
    this.firstname = firstname;
    return this;
  }

   /**
   * Get firstname
   * @return firstname
  **/
  @Schema(description = "")
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public FlightBaseTraveller lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * Get lastname
   * @return lastname
  **/
  @Schema(description = "")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public FlightBaseTraveller nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/
  @Schema(description = "")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public FlightBaseTraveller passportExpirationDate(LocalDate passportExpirationDate) {
    this.passportExpirationDate = passportExpirationDate;
    return this;
  }

   /**
   * Get passportExpirationDate
   * @return passportExpirationDate
  **/
  @Schema(description = "")
  public LocalDate getPassportExpirationDate() {
    return passportExpirationDate;
  }

  public void setPassportExpirationDate(LocalDate passportExpirationDate) {
    this.passportExpirationDate = passportExpirationDate;
  }

  public FlightBaseTraveller passportNumber(String passportNumber) {
    this.passportNumber = passportNumber;
    return this;
  }

   /**
   * Get passportNumber
   * @return passportNumber
  **/
  @Schema(description = "")
  public String getPassportNumber() {
    return passportNumber;
  }

  public void setPassportNumber(String passportNumber) {
    this.passportNumber = passportNumber;
  }

  public FlightBaseTraveller sex(String sex) {
    this.sex = sex;
    return this;
  }

   /**
   * Get sex
   * @return sex
  **/
  @Schema(description = "")
  public String getSex() {
    return sex;
  }

  public void setSex(String sex) {
    this.sex = sex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightBaseTraveller flightBaseTraveller = (FlightBaseTraveller) o;
    return Objects.equals(this.birthDate, flightBaseTraveller.birthDate) &&
        Objects.equals(this.firstname, flightBaseTraveller.firstname) &&
        Objects.equals(this.lastname, flightBaseTraveller.lastname) &&
        Objects.equals(this.nationality, flightBaseTraveller.nationality) &&
        Objects.equals(this.passportExpirationDate, flightBaseTraveller.passportExpirationDate) &&
        Objects.equals(this.passportNumber, flightBaseTraveller.passportNumber) &&
        Objects.equals(this.sex, flightBaseTraveller.sex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(birthDate, firstname, lastname, nationality, passportExpirationDate, passportNumber, sex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightBaseTraveller {\n");
    
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    passportExpirationDate: ").append(toIndentedString(passportExpirationDate)).append("\n");
    sb.append("    passportNumber: ").append(toIndentedString(passportNumber)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
