/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FlightAvailabilitySegment;
import io.swagger.client.model.FlightDepartureAndArrivale;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * FlightAvailabilityResponseBound
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-25T11:48:12.193Z[GMT]")
public class FlightAvailabilityResponseBound {
  @SerializedName("EFT")
  private String EFT = null;

  @SerializedName("airlines")
  private List<String> airlines = null;

  @SerializedName("arrival")
  private FlightDepartureAndArrivale arrival = null;

  @SerializedName("dayDifference")
  private Integer dayDifference = null;

  @SerializedName("departure")
  private FlightDepartureAndArrivale departure = null;

  @SerializedName("flightDuration")
  private Integer flightDuration = null;

  @SerializedName("flightId")
  private Integer flightId = null;

  @SerializedName("nbStops")
  private Integer nbStops = null;

  @SerializedName("segments")
  private List<FlightAvailabilitySegment> segments = null;

  @SerializedName("stopDuration")
  private Integer stopDuration = null;

  @SerializedName("stopoverAirports")
  private List<String> stopoverAirports = null;

  public FlightAvailabilityResponseBound EFT(String EFT) {
    this.EFT = EFT;
    return this;
  }

   /**
   * Get EFT
   * @return EFT
  **/
  @Schema(description = "")
  public String getEFT() {
    return EFT;
  }

  public void setEFT(String EFT) {
    this.EFT = EFT;
  }

  public FlightAvailabilityResponseBound airlines(List<String> airlines) {
    this.airlines = airlines;
    return this;
  }

  public FlightAvailabilityResponseBound addAirlinesItem(String airlinesItem) {
    if (this.airlines == null) {
      this.airlines = new ArrayList<String>();
    }
    this.airlines.add(airlinesItem);
    return this;
  }

   /**
   * Get airlines
   * @return airlines
  **/
  @Schema(description = "")
  public List<String> getAirlines() {
    return airlines;
  }

  public void setAirlines(List<String> airlines) {
    this.airlines = airlines;
  }

  public FlightAvailabilityResponseBound arrival(FlightDepartureAndArrivale arrival) {
    this.arrival = arrival;
    return this;
  }

   /**
   * Get arrival
   * @return arrival
  **/
  @Schema(description = "")
  public FlightDepartureAndArrivale getArrival() {
    return arrival;
  }

  public void setArrival(FlightDepartureAndArrivale arrival) {
    this.arrival = arrival;
  }

  public FlightAvailabilityResponseBound dayDifference(Integer dayDifference) {
    this.dayDifference = dayDifference;
    return this;
  }

   /**
   * Get dayDifference
   * @return dayDifference
  **/
  @Schema(description = "")
  public Integer getDayDifference() {
    return dayDifference;
  }

  public void setDayDifference(Integer dayDifference) {
    this.dayDifference = dayDifference;
  }

  public FlightAvailabilityResponseBound departure(FlightDepartureAndArrivale departure) {
    this.departure = departure;
    return this;
  }

   /**
   * Get departure
   * @return departure
  **/
  @Schema(description = "")
  public FlightDepartureAndArrivale getDeparture() {
    return departure;
  }

  public void setDeparture(FlightDepartureAndArrivale departure) {
    this.departure = departure;
  }

  public FlightAvailabilityResponseBound flightDuration(Integer flightDuration) {
    this.flightDuration = flightDuration;
    return this;
  }

   /**
   * Get flightDuration
   * @return flightDuration
  **/
  @Schema(description = "")
  public Integer getFlightDuration() {
    return flightDuration;
  }

  public void setFlightDuration(Integer flightDuration) {
    this.flightDuration = flightDuration;
  }

  public FlightAvailabilityResponseBound flightId(Integer flightId) {
    this.flightId = flightId;
    return this;
  }

   /**
   * Get flightId
   * @return flightId
  **/
  @Schema(description = "")
  public Integer getFlightId() {
    return flightId;
  }

  public void setFlightId(Integer flightId) {
    this.flightId = flightId;
  }

  public FlightAvailabilityResponseBound nbStops(Integer nbStops) {
    this.nbStops = nbStops;
    return this;
  }

   /**
   * Get nbStops
   * @return nbStops
  **/
  @Schema(description = "")
  public Integer getNbStops() {
    return nbStops;
  }

  public void setNbStops(Integer nbStops) {
    this.nbStops = nbStops;
  }

  public FlightAvailabilityResponseBound segments(List<FlightAvailabilitySegment> segments) {
    this.segments = segments;
    return this;
  }

  public FlightAvailabilityResponseBound addSegmentsItem(FlightAvailabilitySegment segmentsItem) {
    if (this.segments == null) {
      this.segments = new ArrayList<FlightAvailabilitySegment>();
    }
    this.segments.add(segmentsItem);
    return this;
  }

   /**
   * Get segments
   * @return segments
  **/
  @Schema(description = "")
  public List<FlightAvailabilitySegment> getSegments() {
    return segments;
  }

  public void setSegments(List<FlightAvailabilitySegment> segments) {
    this.segments = segments;
  }

  public FlightAvailabilityResponseBound stopDuration(Integer stopDuration) {
    this.stopDuration = stopDuration;
    return this;
  }

   /**
   * Get stopDuration
   * @return stopDuration
  **/
  @Schema(description = "")
  public Integer getStopDuration() {
    return stopDuration;
  }

  public void setStopDuration(Integer stopDuration) {
    this.stopDuration = stopDuration;
  }

  public FlightAvailabilityResponseBound stopoverAirports(List<String> stopoverAirports) {
    this.stopoverAirports = stopoverAirports;
    return this;
  }

  public FlightAvailabilityResponseBound addStopoverAirportsItem(String stopoverAirportsItem) {
    if (this.stopoverAirports == null) {
      this.stopoverAirports = new ArrayList<String>();
    }
    this.stopoverAirports.add(stopoverAirportsItem);
    return this;
  }

   /**
   * Get stopoverAirports
   * @return stopoverAirports
  **/
  @Schema(description = "")
  public List<String> getStopoverAirports() {
    return stopoverAirports;
  }

  public void setStopoverAirports(List<String> stopoverAirports) {
    this.stopoverAirports = stopoverAirports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightAvailabilityResponseBound flightAvailabilityResponseBound = (FlightAvailabilityResponseBound) o;
    return Objects.equals(this.EFT, flightAvailabilityResponseBound.EFT) &&
        Objects.equals(this.airlines, flightAvailabilityResponseBound.airlines) &&
        Objects.equals(this.arrival, flightAvailabilityResponseBound.arrival) &&
        Objects.equals(this.dayDifference, flightAvailabilityResponseBound.dayDifference) &&
        Objects.equals(this.departure, flightAvailabilityResponseBound.departure) &&
        Objects.equals(this.flightDuration, flightAvailabilityResponseBound.flightDuration) &&
        Objects.equals(this.flightId, flightAvailabilityResponseBound.flightId) &&
        Objects.equals(this.nbStops, flightAvailabilityResponseBound.nbStops) &&
        Objects.equals(this.segments, flightAvailabilityResponseBound.segments) &&
        Objects.equals(this.stopDuration, flightAvailabilityResponseBound.stopDuration) &&
        Objects.equals(this.stopoverAirports, flightAvailabilityResponseBound.stopoverAirports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(EFT, airlines, arrival, dayDifference, departure, flightDuration, flightId, nbStops, segments, stopDuration, stopoverAirports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightAvailabilityResponseBound {\n");
    
    sb.append("    EFT: ").append(toIndentedString(EFT)).append("\n");
    sb.append("    airlines: ").append(toIndentedString(airlines)).append("\n");
    sb.append("    arrival: ").append(toIndentedString(arrival)).append("\n");
    sb.append("    dayDifference: ").append(toIndentedString(dayDifference)).append("\n");
    sb.append("    departure: ").append(toIndentedString(departure)).append("\n");
    sb.append("    flightDuration: ").append(toIndentedString(flightDuration)).append("\n");
    sb.append("    flightId: ").append(toIndentedString(flightId)).append("\n");
    sb.append("    nbStops: ").append(toIndentedString(nbStops)).append("\n");
    sb.append("    segments: ").append(toIndentedString(segments)).append("\n");
    sb.append("    stopDuration: ").append(toIndentedString(stopDuration)).append("\n");
    sb.append("    stopoverAirports: ").append(toIndentedString(stopoverAirports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
