/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FlightBaggageAllowance
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-25T18:44:13.943Z[GMT]")
public class FlightBaggageAllowance {
  @SerializedName("freeAllowance")
  private Integer freeAllowance = null;

  @SerializedName("quantityCode")
  private String quantityCode = null;

  @SerializedName("unitQualifier")
  private String unitQualifier = null;

  @SerializedName("withBaggage")
  private Boolean withBaggage = null;

  public FlightBaggageAllowance freeAllowance(Integer freeAllowance) {
    this.freeAllowance = freeAllowance;
    return this;
  }

   /**
   * Get freeAllowance
   * @return freeAllowance
  **/
  @Schema(description = "")
  public Integer getFreeAllowance() {
    return freeAllowance;
  }

  public void setFreeAllowance(Integer freeAllowance) {
    this.freeAllowance = freeAllowance;
  }

  public FlightBaggageAllowance quantityCode(String quantityCode) {
    this.quantityCode = quantityCode;
    return this;
  }

   /**
   * Get quantityCode
   * @return quantityCode
  **/
  @Schema(description = "")
  public String getQuantityCode() {
    return quantityCode;
  }

  public void setQuantityCode(String quantityCode) {
    this.quantityCode = quantityCode;
  }

  public FlightBaggageAllowance unitQualifier(String unitQualifier) {
    this.unitQualifier = unitQualifier;
    return this;
  }

   /**
   * Get unitQualifier
   * @return unitQualifier
  **/
  @Schema(description = "")
  public String getUnitQualifier() {
    return unitQualifier;
  }

  public void setUnitQualifier(String unitQualifier) {
    this.unitQualifier = unitQualifier;
  }

  public FlightBaggageAllowance withBaggage(Boolean withBaggage) {
    this.withBaggage = withBaggage;
    return this;
  }

   /**
   * Get withBaggage
   * @return withBaggage
  **/
  @Schema(description = "")
  public Boolean isWithBaggage() {
    return withBaggage;
  }

  public void setWithBaggage(Boolean withBaggage) {
    this.withBaggage = withBaggage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightBaggageAllowance flightBaggageAllowance = (FlightBaggageAllowance) o;
    return Objects.equals(this.freeAllowance, flightBaggageAllowance.freeAllowance) &&
        Objects.equals(this.quantityCode, flightBaggageAllowance.quantityCode) &&
        Objects.equals(this.unitQualifier, flightBaggageAllowance.unitQualifier) &&
        Objects.equals(this.withBaggage, flightBaggageAllowance.withBaggage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(freeAllowance, quantityCode, unitQualifier, withBaggage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightBaggageAllowance {\n");
    
    sb.append("    freeAllowance: ").append(toIndentedString(freeAllowance)).append("\n");
    sb.append("    quantityCode: ").append(toIndentedString(quantityCode)).append("\n");
    sb.append("    unitQualifier: ").append(toIndentedString(unitQualifier)).append("\n");
    sb.append("    withBaggage: ").append(toIndentedString(withBaggage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
