/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FlightDepartureAndArrivale;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FlightAvailabilitySegment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-24T22:56:10.425Z[GMT]")
public class FlightAvailabilitySegment {
  @SerializedName("arrival")
  private FlightDepartureAndArrivale arrival = null;

  @SerializedName("dayDifference")
  private Integer dayDifference = null;

  @SerializedName("departure")
  private FlightDepartureAndArrivale departure = null;

  @SerializedName("equipmentType")
  private String equipmentType = null;

  @SerializedName("flightOrtrainNumber")
  private String flightOrtrainNumber = null;

  @SerializedName("marketingCarrier")
  private String marketingCarrier = null;

  @SerializedName("operatingCarrier")
  private String operatingCarrier = null;

  public FlightAvailabilitySegment arrival(FlightDepartureAndArrivale arrival) {
    this.arrival = arrival;
    return this;
  }

   /**
   * Get arrival
   * @return arrival
  **/
  @Schema(description = "")
  public FlightDepartureAndArrivale getArrival() {
    return arrival;
  }

  public void setArrival(FlightDepartureAndArrivale arrival) {
    this.arrival = arrival;
  }

  public FlightAvailabilitySegment dayDifference(Integer dayDifference) {
    this.dayDifference = dayDifference;
    return this;
  }

   /**
   * Get dayDifference
   * @return dayDifference
  **/
  @Schema(description = "")
  public Integer getDayDifference() {
    return dayDifference;
  }

  public void setDayDifference(Integer dayDifference) {
    this.dayDifference = dayDifference;
  }

  public FlightAvailabilitySegment departure(FlightDepartureAndArrivale departure) {
    this.departure = departure;
    return this;
  }

   /**
   * Get departure
   * @return departure
  **/
  @Schema(description = "")
  public FlightDepartureAndArrivale getDeparture() {
    return departure;
  }

  public void setDeparture(FlightDepartureAndArrivale departure) {
    this.departure = departure;
  }

  public FlightAvailabilitySegment equipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
    return this;
  }

   /**
   * Get equipmentType
   * @return equipmentType
  **/
  @Schema(description = "")
  public String getEquipmentType() {
    return equipmentType;
  }

  public void setEquipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
  }

  public FlightAvailabilitySegment flightOrtrainNumber(String flightOrtrainNumber) {
    this.flightOrtrainNumber = flightOrtrainNumber;
    return this;
  }

   /**
   * Get flightOrtrainNumber
   * @return flightOrtrainNumber
  **/
  @Schema(description = "")
  public String getFlightOrtrainNumber() {
    return flightOrtrainNumber;
  }

  public void setFlightOrtrainNumber(String flightOrtrainNumber) {
    this.flightOrtrainNumber = flightOrtrainNumber;
  }

  public FlightAvailabilitySegment marketingCarrier(String marketingCarrier) {
    this.marketingCarrier = marketingCarrier;
    return this;
  }

   /**
   * Get marketingCarrier
   * @return marketingCarrier
  **/
  @Schema(description = "")
  public String getMarketingCarrier() {
    return marketingCarrier;
  }

  public void setMarketingCarrier(String marketingCarrier) {
    this.marketingCarrier = marketingCarrier;
  }

  public FlightAvailabilitySegment operatingCarrier(String operatingCarrier) {
    this.operatingCarrier = operatingCarrier;
    return this;
  }

   /**
   * Get operatingCarrier
   * @return operatingCarrier
  **/
  @Schema(description = "")
  public String getOperatingCarrier() {
    return operatingCarrier;
  }

  public void setOperatingCarrier(String operatingCarrier) {
    this.operatingCarrier = operatingCarrier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightAvailabilitySegment flightAvailabilitySegment = (FlightAvailabilitySegment) o;
    return Objects.equals(this.arrival, flightAvailabilitySegment.arrival) &&
        Objects.equals(this.dayDifference, flightAvailabilitySegment.dayDifference) &&
        Objects.equals(this.departure, flightAvailabilitySegment.departure) &&
        Objects.equals(this.equipmentType, flightAvailabilitySegment.equipmentType) &&
        Objects.equals(this.flightOrtrainNumber, flightAvailabilitySegment.flightOrtrainNumber) &&
        Objects.equals(this.marketingCarrier, flightAvailabilitySegment.marketingCarrier) &&
        Objects.equals(this.operatingCarrier, flightAvailabilitySegment.operatingCarrier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arrival, dayDifference, departure, equipmentType, flightOrtrainNumber, marketingCarrier, operatingCarrier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightAvailabilitySegment {\n");
    
    sb.append("    arrival: ").append(toIndentedString(arrival)).append("\n");
    sb.append("    dayDifference: ").append(toIndentedString(dayDifference)).append("\n");
    sb.append("    departure: ").append(toIndentedString(departure)).append("\n");
    sb.append("    equipmentType: ").append(toIndentedString(equipmentType)).append("\n");
    sb.append("    flightOrtrainNumber: ").append(toIndentedString(flightOrtrainNumber)).append("\n");
    sb.append("    marketingCarrier: ").append(toIndentedString(marketingCarrier)).append("\n");
    sb.append("    operatingCarrier: ").append(toIndentedString(operatingCarrier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
