/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * HotelAvailabilityRequestFilter
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-27T12:15:25.449Z[GMT]")
public class HotelAvailabilityRequestFilter {
  @SerializedName("maxHotels")
  private Integer maxHotels = null;

  @SerializedName("paymentType")
  private String paymentType = null;

  public HotelAvailabilityRequestFilter maxHotels(Integer maxHotels) {
    this.maxHotels = maxHotels;
    return this;
  }

   /**
   * Get maxHotels
   * @return maxHotels
  **/
  @Schema(example = "500", description = "")
  public Integer getMaxHotels() {
    return maxHotels;
  }

  public void setMaxHotels(Integer maxHotels) {
    this.maxHotels = maxHotels;
  }

  public HotelAvailabilityRequestFilter paymentType(String paymentType) {
    this.paymentType = paymentType;
    return this;
  }

   /**
   * Get paymentType
   * @return paymentType
  **/
  @Schema(example = "AT_WEB", description = "")
  public String getPaymentType() {
    return paymentType;
  }

  public void setPaymentType(String paymentType) {
    this.paymentType = paymentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelAvailabilityRequestFilter hotelAvailabilityRequestFilter = (HotelAvailabilityRequestFilter) o;
    return Objects.equals(this.maxHotels, hotelAvailabilityRequestFilter.maxHotels) &&
        Objects.equals(this.paymentType, hotelAvailabilityRequestFilter.paymentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxHotels, paymentType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelAvailabilityRequestFilter {\n");
    
    sb.append("    maxHotels: ").append(toIndentedString(maxHotels)).append("\n");
    sb.append("    paymentType: ").append(toIndentedString(paymentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
