/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.HotelCancellationPolicy;
import io.swagger.client.model.HotelConfirmationResponseBookingHotelPaxes;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * HotelCancellationResponseBookingHotelRooms
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-25T11:48:12.193Z[GMT]")
public class HotelCancellationResponseBookingHotelRooms {
  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("rateComment")
  private String rateComment = null;

  @SerializedName("boardName")
  private String boardName = null;

  @SerializedName("boardCode")
  private String boardCode = null;

  @SerializedName("price")
  private Integer price = null;

  @SerializedName("adults")
  private Integer adults = null;

  @SerializedName("children")
  private Integer children = null;

  @SerializedName("cancellationPolicies")
  private List<HotelCancellationPolicy> cancellationPolicies = null;

  @SerializedName("paxes")
  private List<HotelConfirmationResponseBookingHotelPaxes> paxes = null;

  public HotelCancellationResponseBookingHotelRooms code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public HotelCancellationResponseBookingHotelRooms name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public HotelCancellationResponseBookingHotelRooms rateComment(String rateComment) {
    this.rateComment = rateComment;
    return this;
  }

   /**
   * Get rateComment
   * @return rateComment
  **/
  @Schema(description = "")
  public String getRateComment() {
    return rateComment;
  }

  public void setRateComment(String rateComment) {
    this.rateComment = rateComment;
  }

  public HotelCancellationResponseBookingHotelRooms boardName(String boardName) {
    this.boardName = boardName;
    return this;
  }

   /**
   * Get boardName
   * @return boardName
  **/
  @Schema(description = "")
  public String getBoardName() {
    return boardName;
  }

  public void setBoardName(String boardName) {
    this.boardName = boardName;
  }

  public HotelCancellationResponseBookingHotelRooms boardCode(String boardCode) {
    this.boardCode = boardCode;
    return this;
  }

   /**
   * Get boardCode
   * @return boardCode
  **/
  @Schema(description = "")
  public String getBoardCode() {
    return boardCode;
  }

  public void setBoardCode(String boardCode) {
    this.boardCode = boardCode;
  }

  public HotelCancellationResponseBookingHotelRooms price(Integer price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public HotelCancellationResponseBookingHotelRooms adults(Integer adults) {
    this.adults = adults;
    return this;
  }

   /**
   * Get adults
   * @return adults
  **/
  @Schema(description = "")
  public Integer getAdults() {
    return adults;
  }

  public void setAdults(Integer adults) {
    this.adults = adults;
  }

  public HotelCancellationResponseBookingHotelRooms children(Integer children) {
    this.children = children;
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @Schema(description = "")
  public Integer getChildren() {
    return children;
  }

  public void setChildren(Integer children) {
    this.children = children;
  }

  public HotelCancellationResponseBookingHotelRooms cancellationPolicies(List<HotelCancellationPolicy> cancellationPolicies) {
    this.cancellationPolicies = cancellationPolicies;
    return this;
  }

  public HotelCancellationResponseBookingHotelRooms addCancellationPoliciesItem(HotelCancellationPolicy cancellationPoliciesItem) {
    if (this.cancellationPolicies == null) {
      this.cancellationPolicies = new ArrayList<HotelCancellationPolicy>();
    }
    this.cancellationPolicies.add(cancellationPoliciesItem);
    return this;
  }

   /**
   * Get cancellationPolicies
   * @return cancellationPolicies
  **/
  @Schema(description = "")
  public List<HotelCancellationPolicy> getCancellationPolicies() {
    return cancellationPolicies;
  }

  public void setCancellationPolicies(List<HotelCancellationPolicy> cancellationPolicies) {
    this.cancellationPolicies = cancellationPolicies;
  }

  public HotelCancellationResponseBookingHotelRooms paxes(List<HotelConfirmationResponseBookingHotelPaxes> paxes) {
    this.paxes = paxes;
    return this;
  }

  public HotelCancellationResponseBookingHotelRooms addPaxesItem(HotelConfirmationResponseBookingHotelPaxes paxesItem) {
    if (this.paxes == null) {
      this.paxes = new ArrayList<HotelConfirmationResponseBookingHotelPaxes>();
    }
    this.paxes.add(paxesItem);
    return this;
  }

   /**
   * Get paxes
   * @return paxes
  **/
  @Schema(description = "")
  public List<HotelConfirmationResponseBookingHotelPaxes> getPaxes() {
    return paxes;
  }

  public void setPaxes(List<HotelConfirmationResponseBookingHotelPaxes> paxes) {
    this.paxes = paxes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelCancellationResponseBookingHotelRooms hotelCancellationResponseBookingHotelRooms = (HotelCancellationResponseBookingHotelRooms) o;
    return Objects.equals(this.code, hotelCancellationResponseBookingHotelRooms.code) &&
        Objects.equals(this.name, hotelCancellationResponseBookingHotelRooms.name) &&
        Objects.equals(this.rateComment, hotelCancellationResponseBookingHotelRooms.rateComment) &&
        Objects.equals(this.boardName, hotelCancellationResponseBookingHotelRooms.boardName) &&
        Objects.equals(this.boardCode, hotelCancellationResponseBookingHotelRooms.boardCode) &&
        Objects.equals(this.price, hotelCancellationResponseBookingHotelRooms.price) &&
        Objects.equals(this.adults, hotelCancellationResponseBookingHotelRooms.adults) &&
        Objects.equals(this.children, hotelCancellationResponseBookingHotelRooms.children) &&
        Objects.equals(this.cancellationPolicies, hotelCancellationResponseBookingHotelRooms.cancellationPolicies) &&
        Objects.equals(this.paxes, hotelCancellationResponseBookingHotelRooms.paxes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, rateComment, boardName, boardCode, price, adults, children, cancellationPolicies, paxes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelCancellationResponseBookingHotelRooms {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rateComment: ").append(toIndentedString(rateComment)).append("\n");
    sb.append("    boardName: ").append(toIndentedString(boardName)).append("\n");
    sb.append("    boardCode: ").append(toIndentedString(boardCode)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    adults: ").append(toIndentedString(adults)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    cancellationPolicies: ").append(toIndentedString(cancellationPolicies)).append("\n");
    sb.append("    paxes: ").append(toIndentedString(paxes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
