/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.HotelAvailabilityResponseHotelsImages;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * HotelAvailabilityResponseHotelsRooms
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-27T12:15:25.449Z[GMT]")
public class HotelAvailabilityResponseHotelsRooms {
  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("images")
  private List<HotelAvailabilityResponseHotelsImages> images = null;

  @SerializedName("adults")
  private Integer adults = null;

  @SerializedName("children")
  private Integer children = null;

  @SerializedName("maxPeople")
  private Integer maxPeople = null;

  @SerializedName("availability")
  private Integer availability = null;

  public HotelAvailabilityResponseHotelsRooms code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public HotelAvailabilityResponseHotelsRooms name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public HotelAvailabilityResponseHotelsRooms description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public HotelAvailabilityResponseHotelsRooms images(List<HotelAvailabilityResponseHotelsImages> images) {
    this.images = images;
    return this;
  }

  public HotelAvailabilityResponseHotelsRooms addImagesItem(HotelAvailabilityResponseHotelsImages imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<HotelAvailabilityResponseHotelsImages>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @Schema(description = "")
  public List<HotelAvailabilityResponseHotelsImages> getImages() {
    return images;
  }

  public void setImages(List<HotelAvailabilityResponseHotelsImages> images) {
    this.images = images;
  }

  public HotelAvailabilityResponseHotelsRooms adults(Integer adults) {
    this.adults = adults;
    return this;
  }

   /**
   * Get adults
   * @return adults
  **/
  @Schema(description = "")
  public Integer getAdults() {
    return adults;
  }

  public void setAdults(Integer adults) {
    this.adults = adults;
  }

  public HotelAvailabilityResponseHotelsRooms children(Integer children) {
    this.children = children;
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @Schema(description = "")
  public Integer getChildren() {
    return children;
  }

  public void setChildren(Integer children) {
    this.children = children;
  }

  public HotelAvailabilityResponseHotelsRooms maxPeople(Integer maxPeople) {
    this.maxPeople = maxPeople;
    return this;
  }

   /**
   * Get maxPeople
   * @return maxPeople
  **/
  @Schema(description = "")
  public Integer getMaxPeople() {
    return maxPeople;
  }

  public void setMaxPeople(Integer maxPeople) {
    this.maxPeople = maxPeople;
  }

  public HotelAvailabilityResponseHotelsRooms availability(Integer availability) {
    this.availability = availability;
    return this;
  }

   /**
   * Get availability
   * @return availability
  **/
  @Schema(description = "")
  public Integer getAvailability() {
    return availability;
  }

  public void setAvailability(Integer availability) {
    this.availability = availability;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelAvailabilityResponseHotelsRooms hotelAvailabilityResponseHotelsRooms = (HotelAvailabilityResponseHotelsRooms) o;
    return Objects.equals(this.code, hotelAvailabilityResponseHotelsRooms.code) &&
        Objects.equals(this.name, hotelAvailabilityResponseHotelsRooms.name) &&
        Objects.equals(this.description, hotelAvailabilityResponseHotelsRooms.description) &&
        Objects.equals(this.images, hotelAvailabilityResponseHotelsRooms.images) &&
        Objects.equals(this.adults, hotelAvailabilityResponseHotelsRooms.adults) &&
        Objects.equals(this.children, hotelAvailabilityResponseHotelsRooms.children) &&
        Objects.equals(this.maxPeople, hotelAvailabilityResponseHotelsRooms.maxPeople) &&
        Objects.equals(this.availability, hotelAvailabilityResponseHotelsRooms.availability);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, description, images, adults, children, maxPeople, availability);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelAvailabilityResponseHotelsRooms {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    adults: ").append(toIndentedString(adults)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    maxPeople: ").append(toIndentedString(maxPeople)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
