/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AlgebratecResponse;
import io.swagger.client.model.Error;
import io.swagger.client.model.HotelAvailabilityResponseHotels;
import io.swagger.client.model.Supplier;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * HotelAvailabilityResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-24T22:56:10.425Z[GMT]")
public class HotelAvailabilityResponse extends AlgebratecResponse {
  @SerializedName("hotels")
  private HotelAvailabilityResponseHotels hotels = null;

  @SerializedName("suppliers")
  private List<Supplier> suppliers = null;

  public HotelAvailabilityResponse hotels(HotelAvailabilityResponseHotels hotels) {
    this.hotels = hotels;
    return this;
  }

   /**
   * Get hotels
   * @return hotels
  **/
  @Schema(description = "")
  public HotelAvailabilityResponseHotels getHotels() {
    return hotels;
  }

  public void setHotels(HotelAvailabilityResponseHotels hotels) {
    this.hotels = hotels;
  }

  public HotelAvailabilityResponse suppliers(List<Supplier> suppliers) {
    this.suppliers = suppliers;
    return this;
  }

  public HotelAvailabilityResponse addSuppliersItem(Supplier suppliersItem) {
    if (this.suppliers == null) {
      this.suppliers = new ArrayList<Supplier>();
    }
    this.suppliers.add(suppliersItem);
    return this;
  }

   /**
   * Get suppliers
   * @return suppliers
  **/
  @Schema(description = "")
  public List<Supplier> getSuppliers() {
    return suppliers;
  }

  public void setSuppliers(List<Supplier> suppliers) {
    this.suppliers = suppliers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelAvailabilityResponse hotelAvailabilityResponse = (HotelAvailabilityResponse) o;
    return Objects.equals(this.hotels, hotelAvailabilityResponse.hotels) &&
        Objects.equals(this.suppliers, hotelAvailabilityResponse.suppliers) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hotels, suppliers, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelAvailabilityResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    hotels: ").append(toIndentedString(hotels)).append("\n");
    sb.append("    suppliers: ").append(toIndentedString(suppliers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
