/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.HotelConfirmationRequestPaxes;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * HotelConfirmationRequestRooms
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-27T12:15:25.449Z[GMT]")
public class HotelConfirmationRequestRooms {
  @SerializedName("rateKey")
  private String rateKey = null;

  @SerializedName("paxes")
  private List<HotelConfirmationRequestPaxes> paxes = null;

  public HotelConfirmationRequestRooms rateKey(String rateKey) {
    this.rateKey = rateKey;
    return this;
  }

   /**
   * Get rateKey
   * @return rateKey
  **/
  @Schema(description = "")
  public String getRateKey() {
    return rateKey;
  }

  public void setRateKey(String rateKey) {
    this.rateKey = rateKey;
  }

  public HotelConfirmationRequestRooms paxes(List<HotelConfirmationRequestPaxes> paxes) {
    this.paxes = paxes;
    return this;
  }

  public HotelConfirmationRequestRooms addPaxesItem(HotelConfirmationRequestPaxes paxesItem) {
    if (this.paxes == null) {
      this.paxes = new ArrayList<HotelConfirmationRequestPaxes>();
    }
    this.paxes.add(paxesItem);
    return this;
  }

   /**
   * Get paxes
   * @return paxes
  **/
  @Schema(description = "")
  public List<HotelConfirmationRequestPaxes> getPaxes() {
    return paxes;
  }

  public void setPaxes(List<HotelConfirmationRequestPaxes> paxes) {
    this.paxes = paxes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelConfirmationRequestRooms hotelConfirmationRequestRooms = (HotelConfirmationRequestRooms) o;
    return Objects.equals(this.rateKey, hotelConfirmationRequestRooms.rateKey) &&
        Objects.equals(this.paxes, hotelConfirmationRequestRooms.paxes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rateKey, paxes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelConfirmationRequestRooms {\n");
    
    sb.append("    rateKey: ").append(toIndentedString(rateKey)).append("\n");
    sb.append("    paxes: ").append(toIndentedString(paxes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
