/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AlgebratecResponse;
import io.swagger.client.model.Error;
import io.swagger.client.model.HotelRetrieveBookingResponseBooking;
import io.swagger.client.model.Supplier;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * HotelRetrieveBookingResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-24T22:56:10.425Z[GMT]")
public class HotelRetrieveBookingResponse extends AlgebratecResponse {
  @SerializedName("booking")
  private HotelRetrieveBookingResponseBooking booking = null;

  @SerializedName("suppliers")
  private List<Supplier> suppliers = null;

  public HotelRetrieveBookingResponse booking(HotelRetrieveBookingResponseBooking booking) {
    this.booking = booking;
    return this;
  }

   /**
   * Get booking
   * @return booking
  **/
  @Schema(description = "")
  public HotelRetrieveBookingResponseBooking getBooking() {
    return booking;
  }

  public void setBooking(HotelRetrieveBookingResponseBooking booking) {
    this.booking = booking;
  }

  public HotelRetrieveBookingResponse suppliers(List<Supplier> suppliers) {
    this.suppliers = suppliers;
    return this;
  }

  public HotelRetrieveBookingResponse addSuppliersItem(Supplier suppliersItem) {
    if (this.suppliers == null) {
      this.suppliers = new ArrayList<Supplier>();
    }
    this.suppliers.add(suppliersItem);
    return this;
  }

   /**
   * Get suppliers
   * @return suppliers
  **/
  @Schema(description = "")
  public List<Supplier> getSuppliers() {
    return suppliers;
  }

  public void setSuppliers(List<Supplier> suppliers) {
    this.suppliers = suppliers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelRetrieveBookingResponse hotelRetrieveBookingResponse = (HotelRetrieveBookingResponse) o;
    return Objects.equals(this.booking, hotelRetrieveBookingResponse.booking) &&
        Objects.equals(this.suppliers, hotelRetrieveBookingResponse.suppliers) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(booking, suppliers, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelRetrieveBookingResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    booking: ").append(toIndentedString(booking)).append("\n");
    sb.append("    suppliers: ").append(toIndentedString(suppliers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
