/*
 * Algebratec API
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AlgebratecResponse;
import io.swagger.client.model.HotelAvailabilityRequest;
import io.swagger.client.model.HotelAvailabilityResponse;
import io.swagger.client.model.HotelCancellationResponse;
import io.swagger.client.model.HotelCheckRatesRequest;
import io.swagger.client.model.HotelCheckRatesResponse;
import io.swagger.client.model.HotelConfirmationRequest;
import io.swagger.client.model.HotelConfirmationResponse;
import io.swagger.client.model.HotelRetrieveBookingResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HotelApi
 */
@Ignore
public class HotelApiTest {

    private final HotelApi api = new HotelApi();

    /**
     * list bookable hotels
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hotelAvailabilityTest() throws ApiException {
        HotelAvailabilityRequest body = null;
        HotelAvailabilityResponse response = api.hotelAvailability(body);

        // TODO: test validations
    }
    /**
     * cancel hotel booking
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hotelBookingCancellationTest() throws ApiException {
        String reference = null;
        Boolean SIMULATION = null;
        String language = null;
        HotelCancellationResponse response = api.hotelBookingCancellation(reference, SIMULATION, language);

        // TODO: test validations
    }
    /**
     * confirm hotel booking
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hotelBookingConfirmationTest() throws ApiException {
        HotelConfirmationRequest body = null;
        HotelConfirmationResponse response = api.hotelBookingConfirmation(body);

        // TODO: test validations
    }
    /**
     * check hotel rating
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hotelCheckRateTest() throws ApiException {
        HotelCheckRatesRequest body = null;
        HotelCheckRatesResponse response = api.hotelCheckRate(body);

        // TODO: test validations
    }
    /**
     * retrieve hotel booking
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hotelRetrieveBookingTest() throws ApiException {
        String reference = null;
        String language = null;
        HotelRetrieveBookingResponse response = api.hotelRetrieveBooking(reference, language);

        // TODO: test validations
    }
}
